---
- name: Add VLANs from YAML
  hosts: leafs
  vars_files:
    - vlans.yml
  tasks:
    - name: Add VLANs from VLAN
      arista.eos.eos_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
      loop: "{{ vlans_list }}"
